include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
linter:
  # producing the lint.
  rules:
    prefer_relative_imports: true
    prefer_void_to_null: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    #- avoid_dynamic_calls: true
    avoid_empty_else: true
    empty_catches: true
    exhaustive_cases: true
    prefer_final_fields: true
    #- prefer_final_locals: true
    #- prefer_final_in_for_each: true
    #- prefer_final_parameters: true
    prefer_for_elements_to_map_fromIterable: true
    #- unnecessary_await_in_return: true
    prefer_contains: true
    avoid_redundant_argument_values: true
    avoid_catching_errors: true
    #- prefer_foreach: true
    #- always_put_required_named_parameters_first: true
    use_key_in_widget_constructors: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    prefer_const_constructors: true
    use_decorated_box: true
    use_full_hex_values_for_flutter_colors: true
    unawaited_futures: true
    require_trailing_commas: true
    cancel_subscriptions: true
    close_sinks: true
    ############################## Disabled Rules ##############################
    slash_for_doc_comments: false
    dangling_library_doc_comments: false
